notifications:
  slack:
    secure: CoWFd3PCTh1B3n4uH6ZmvaVKiXRlpfYRpdOeb+kRREVWhodr2TICJWeD/j8WHcEbMf87nGls1qU9WYgk3j1edp7YokXFLKvGgLbpCNL3Aa5ET3s7DY/VWpWopIuG4LPT5bL3ka7iZZvqoQbfUUlPdgGWeAx8R1GMCElXqlwjBpPsBpg0c/bjIb34VMT8P57yh+n+4iv+XvSruesnbkoZYqL6b1samVqhtcMV6816wajgiXN4LKkJ03l/2zxbN0003utdVsmhNuyYw9UADYhRdVRoVj1L1i1dJ5a9nsXtNwfTm7LIeAdupi6m61WUWUZQp9cefYydIZlx3QUAbJOT3YeNCfX7jxWhuZHravC4bVZQ5sb+BFSllqEzsPpqhaqTYYJ3/avmU8UCfsGlJUkXp2OfN/ofoVl+ibPxioAtb2J5UBDL5Ar3NU7v2qX8TYITUHivlmXvhsnGdoE40WQnnU8vZTetWyeQEPbieLn5umOycSZqE82SnfCYd0YhTPUGSfjF3hL+9KpN/pdX4RPJgSh2GMtSDhoLHCH6y8PfhlWzaNkOQH/vviOXsMU/GUjmKb7g1ozYpW5XkO50D+0SmSwx2oyplP1NnrRHmIn83C8imQLPg1rmLjLBBsvSVP4stPQ9A3UIaOxzMKbVulQqC+zJNLhyTHuewd+4eovaXdI=
addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
script:
- binaries/hugo
deploy:
  provider: s3
  bucket: automaticdev.team
  region: us-east-1
  local_dir: public
  skip_cleanup: true
  acl: public_read
  access_key_id: AKIAJDCW7VJVH6ITDFAQ
  secret_access_key:    
     secure: "XmlilDsJyFr9yZIj3ftY8BGoRHMhfTRMxG55skHnDdBSVZYKmSnaXugVpWX+to67zzlkbz8NP53B17mpYG0ZPSQvhrvv5dlZtU+UQHnUcpU/ASLAv8+9mNBhOr1xsmzgTpdgnQbHTdorVCtPFlqUXNkiXKfU5Bcp/t7pqvgkJGN5r2Azi0qfeVjMmA0lqBCzukm1UA/QmKy/q+gtpxN97R9zjPW/1LmHQN/299JDjasG5dxFySMbGGQ8WXdX7REpSxonNXWbiiQEe+d8/u+qirV2DfCPn0rb8lb72zHwRJGHyOCyjs66sMJ+dNgBCZWnMyjyd8AYDCWdoqu4z+j9kUdssPHoukvfy9NyOMVAIGxmHkhf1BwsHiIg8pIgO0/alf3FS/xGPpybP6ziY891RqRrV1J6LJ82/ybU9cT0ETQBYsZdYvUm2oq44fflWbk6PAcPEojaOc/Bd1FGmWHP5OYp/bc6GPrlb7sIH2wCezamj+8wWZ8wNxCke126J/0rk5kv4QH/22N+m1LNzg5QZmbnL2mnqxYmPM6Toxv3WiQWnITaTHoQbcFcrxJshIjhwfbKo3IBVGuvTly5VoHMTXwYKHCbX3RMR+jws6XydlJBUEXtT0DfaMbtjyaaWospw3p/EfHVYcNUxTx6Lch6pm/74uM/rnmBfSFl3dIqm1s="
