notifications:
  slack:
    secure: CoWFd3PCTh1B3n4uH6ZmvaVKiXRlpfYRpdOeb+kRREVWhodr2TICJWeD/j8WHcEbMf87nGls1qU9WYgk3j1edp7YokXFLKvGgLbpCNL3Aa5ET3s7DY/VWpWopIuG4LPT5bL3ka7iZZvqoQbfUUlPdgGWeAx8R1GMCElXqlwjBpPsBpg0c/bjIb34VMT8P57yh+n+4iv+XvSruesnbkoZYqL6b1samVqhtcMV6816wajgiXN4LKkJ03l/2zxbN0003utdVsmhNuyYw9UADYhRdVRoVj1L1i1dJ5a9nsXtNwfTm7LIeAdupi6m61WUWUZQp9cefYydIZlx3QUAbJOT3YeNCfX7jxWhuZHravC4bVZQ5sb+BFSllqEzsPpqhaqTYYJ3/avmU8UCfsGlJUkXp2OfN/ofoVl+ibPxioAtb2J5UBDL5Ar3NU7v2qX8TYITUHivlmXvhsnGdoE40WQnnU8vZTetWyeQEPbieLn5umOycSZqE82SnfCYd0YhTPUGSfjF3hL+9KpN/pdX4RPJgSh2GMtSDhoLHCH6y8PfhlWzaNkOQH/vviOXsMU/GUjmKb7g1ozYpW5XkO50D+0SmSwx2oyplP1NnrRHmIn83C8imQLPg1rmLjLBBsvSVP4stPQ9A3UIaOxzMKbVulQqC+zJNLhyTHuewd+4eovaXdI=
addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
script:
- binaries/hugo
deploy:
  provider: s3
  bucket: automaticdev.team
  region: us-east-1
  local_dir: public
  skip_cleanup: true
  acl: public_read
  access_key_id: AKIAJDCW7VJVH6ITDFAQ
  secret_access_key:
    secure: ZYT5Lrkaqo3MqLDs/2wGMDX3JlBpa4NCncPtNJ0lO5L5rDOOXh7897qfMN0yUHylRLNOqHqFA36IgSlN0NvpWDufaNf9wzal05MCJSCrx8dBCV3yoOjiK84b78ixRh7cRBtoQLoQPLE5GqViNq/zx1oRd1gmZQWPcVt+s0bL8Jju6FJQLNdp4ohz2/Dm3KikmdPRzGBxLsVv1U9bD16DW0cqjCJbROMFvY7Gp2SRo9ERimByreOJD8uJwobxVHZLCQFB5Knf+mAjVCWuvnuHaDHVZhRCL01MZ84d+fuLdEYJyOWgAfbXDp3VfmGBeGD8VOQ9M/rO86ybQyeImp0GUrOZufywBOjkh94ELliSAIEDPhFmlYszYqlNs/GlD0JJzHQKrGvcm4f1YLCbPSZm5dL2zjeUWEZt7E8eg99svHzH0PPvWOSEiGltnsr/kft4jQPS/ItqYRCxsLAmMkDTUQZ0niygvpNd1An8iUC32Kbj3NOy39GcUvIbB8izE6uI/G97/dH12k6f9r6mgTctExHKiuVdQcuHod992zn1NVbYtZFjfH93LK+kWc9GrclSbVUNnyPAX9kYCT/FJGshbaDDar63De0reKrbJw1TGBy9AfEMWV88+dE3cCQfTTRTvQ3Kf+FvAqRbzzptlecBhSv3FsZAnx/nlf9yzDXViUI=
