notifications:
  slack:
    secure: CoWFd3PCTh1B3n4uH6ZmvaVKiXRlpfYRpdOeb+kRREVWhodr2TICJWeD/j8WHcEbMf87nGls1qU9WYgk3j1edp7YokXFLKvGgLbpCNL3Aa5ET3s7DY/VWpWopIuG4LPT5bL3ka7iZZvqoQbfUUlPdgGWeAx8R1GMCElXqlwjBpPsBpg0c/bjIb34VMT8P57yh+n+4iv+XvSruesnbkoZYqL6b1samVqhtcMV6816wajgiXN4LKkJ03l/2zxbN0003utdVsmhNuyYw9UADYhRdVRoVj1L1i1dJ5a9nsXtNwfTm7LIeAdupi6m61WUWUZQp9cefYydIZlx3QUAbJOT3YeNCfX7jxWhuZHravC4bVZQ5sb+BFSllqEzsPpqhaqTYYJ3/avmU8UCfsGlJUkXp2OfN/ofoVl+ibPxioAtb2J5UBDL5Ar3NU7v2qX8TYITUHivlmXvhsnGdoE40WQnnU8vZTetWyeQEPbieLn5umOycSZqE82SnfCYd0YhTPUGSfjF3hL+9KpN/pdX4RPJgSh2GMtSDhoLHCH6y8PfhlWzaNkOQH/vviOXsMU/GUjmKb7g1ozYpW5XkO50D+0SmSwx2oyplP1NnrRHmIn83C8imQLPg1rmLjLBBsvSVP4stPQ9A3UIaOxzMKbVulQqC+zJNLhyTHuewd+4eovaXdI=
addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
script:
- binaries/hugo
deploy:
  provider: s3
  bucket: automaticdev.team
  region: us-east-1
  local_dir: public
  skip_cleanup: true
  acl: public_read
  access_key_id: AKIAYP2YIAYM2M7D6TMG
  secret_access_key:
    secure: KETDA6L/kmbCVhZGOLeHStdQN8ZBIdiuTeQuvm0MuKVaCGS8f8MUeEQI7I2jq7zOOvYgs5e7AYTrKjvAQJuYHGzoIOBNX85D0f9hvoKaq+31fpqmtv999vTHurqfUvW6qsvR2kh8kgD6x45Ya1lTZ3YXIH39lJUc/A78g2B/WQHGkw0LMqCqBChnecmdCgh2f+Z3X2qCnWscbQlCUBq2roe7o0uEW0i+SpeVqNfnxaj7I8WUWCYVsn9TS17BM9pJ3wk+Ut+unNFozwkdtdL5WJvRZ/fhB06GI4pFdnaOInnTJwFavNqj8hjHCh1u6fDyd5KUlF9RldM4u7d6oWkECOKZmMTz4nFtsrCC6cZAZw2kJHuHhOemZqYecWyjDxh5QPZg6GUz/MfPBDNfBlFbppZYif+iUAr2Pt7eqP9G+L2ZdL3h07D/JGumU51bpRlqwRNpFKkNWZLL/DTwW+1f5rW4nGwZidKyAPMK/sVeWbpRdzy5TNmYqn/WCMuyez298mulZ3y5Wm4QbZMni7f43o4J0rBYITeIJYfyo9S5DkXWc3uyc1Cumx7DCDJB0bNxmWZLq96rbxbX/D2OTlmRHjRBFpvUfg3IsT8HA5s6N5cEaKCxwy6BmpG+jHnBpoPgl9i/mVPXUWIJMGEWffNu2I2weaD4sRFfJ9yiN+pSxv8=
