notifications:
  slack:
    secure: CoWFd3PCTh1B3n4uH6ZmvaVKiXRlpfYRpdOeb+kRREVWhodr2TICJWeD/j8WHcEbMf87nGls1qU9WYgk3j1edp7YokXFLKvGgLbpCNL3Aa5ET3s7DY/VWpWopIuG4LPT5bL3ka7iZZvqoQbfUUlPdgGWeAx8R1GMCElXqlwjBpPsBpg0c/bjIb34VMT8P57yh+n+4iv+XvSruesnbkoZYqL6b1samVqhtcMV6816wajgiXN4LKkJ03l/2zxbN0003utdVsmhNuyYw9UADYhRdVRoVj1L1i1dJ5a9nsXtNwfTm7LIeAdupi6m61WUWUZQp9cefYydIZlx3QUAbJOT3YeNCfX7jxWhuZHravC4bVZQ5sb+BFSllqEzsPpqhaqTYYJ3/avmU8UCfsGlJUkXp2OfN/ofoVl+ibPxioAtb2J5UBDL5Ar3NU7v2qX8TYITUHivlmXvhsnGdoE40WQnnU8vZTetWyeQEPbieLn5umOycSZqE82SnfCYd0YhTPUGSfjF3hL+9KpN/pdX4RPJgSh2GMtSDhoLHCH6y8PfhlWzaNkOQH/vviOXsMU/GUjmKb7g1ozYpW5XkO50D+0SmSwx2oyplP1NnrRHmIn83C8imQLPg1rmLjLBBsvSVP4stPQ9A3UIaOxzMKbVulQqC+zJNLhyTHuewd+4eovaXdI=
addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
script:
- binaries/hugo
deploy:
  provider: s3
  bucket: cloudshock.io
  region: us-east-1
  local_dir: public
  skip_cleanup: true
  acl: public_read
  access_key_id: AKIAJDCW7VJVH6ITDFAQ
  secret_access_key:
    secure: ernhLuAell8wacrFqLUUw2vxv0R3yjgKQxkEroZ9q+044425dTU9kJh8kVfBur/grMM42ABC04Y9jNRP4ldd0823VIML5HICnhN+BhB12TBdbLGRi9ChPDuKWVzDhd2YRGlG+feWm+9dyk7sTJ4G3aA2vDfZ6x+TIFMM87p9RtpCC7ZeyymF9oSUfJya1biH/OWuPqpl5TFeRGkeTX1NhCkXyuvaHydSNuMdDqqtMA9jppKjPVyahWvlRTk1x+TW0cCCtYnI7jCdw4mJmOpL4nwu3gneZOrzpOHT1nQpg2ZvsR2Crc2rm2FmPksF9Zg/yOYnbRqmmgYqLTJzirQptn06o4yq7OYfv5DYX55YFAwdL+HVbe2WVwX3Xn7wh9UcGV8AUvJAW0F5wbfI8c1lsy23fMIuU0vN/bMaVhftvwd1N/06qm8Ij0LnbPtYI7ep1WR4AnlIGAwf3XtFqnEQ4Q+CN6AV0kj9iUGPKCg07C6gItqy35Mah8lSh/tQfJhY5gbhrjMV5kyEPjGC8zxEmu3Uwb96ob9LFvmXYIQNCO3TnEhT93+u+aC3GVtv3Qzoy+POL+7qJ1gWC8Uw33Gu52a0njCsI6dAm9dYwG0+x8m+gzM5kfBNfjVgM2MGwQWCZcbQH8I4AnkiUUNvzj6c3FcDh+bYx5Ops3hONSCNmfs=
