notifications:
  slack:
    secure: CoWFd3PCTh1B3n4uH6ZmvaVKiXRlpfYRpdOeb+kRREVWhodr2TICJWeD/j8WHcEbMf87nGls1qU9WYgk3j1edp7YokXFLKvGgLbpCNL3Aa5ET3s7DY/VWpWopIuG4LPT5bL3ka7iZZvqoQbfUUlPdgGWeAx8R1GMCElXqlwjBpPsBpg0c/bjIb34VMT8P57yh+n+4iv+XvSruesnbkoZYqL6b1samVqhtcMV6816wajgiXN4LKkJ03l/2zxbN0003utdVsmhNuyYw9UADYhRdVRoVj1L1i1dJ5a9nsXtNwfTm7LIeAdupi6m61WUWUZQp9cefYydIZlx3QUAbJOT3YeNCfX7jxWhuZHravC4bVZQ5sb+BFSllqEzsPpqhaqTYYJ3/avmU8UCfsGlJUkXp2OfN/ofoVl+ibPxioAtb2J5UBDL5Ar3NU7v2qX8TYITUHivlmXvhsnGdoE40WQnnU8vZTetWyeQEPbieLn5umOycSZqE82SnfCYd0YhTPUGSfjF3hL+9KpN/pdX4RPJgSh2GMtSDhoLHCH6y8PfhlWzaNkOQH/vviOXsMU/GUjmKb7g1ozYpW5XkO50D+0SmSwx2oyplP1NnrRHmIn83C8imQLPg1rmLjLBBsvSVP4stPQ9A3UIaOxzMKbVulQqC+zJNLhyTHuewd+4eovaXdI=
addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
script:
- binaries/hugo
deploy:
  provider: s3
  bucket: automaticdev.team
  region: us-east-1
  local_dir: public
  skip_cleanup: true
  acl: public_read
  access_key_id: AKIAJDCW7VJVH6ITDFAQ
  secret_access_key:
    secure: NDwLvgItH4KzTWib1J5JtuIrZDcQOjvTVlhbHw0MZ0Yob0VgaVxhpy4jgnxmZ3wYtNh7Dx+r19qdCARQBvtoM9uSXryT4H05AO1O5cF7oBsauKuEsrHvKWltzbJig/Kcq5nGJyoLUS9EKlxgYrOzd2PcfgZRaozCkbmS1uord6qEiqbkyIIyJln1qUptKvMkSI93zNbPz+mOw834QF/5bCizXng3Cp42zsW7mcAdCW+YMIfvWLvnqKTaf+CClRl3yXw/ozZFZ8EVPfyOiAZy07dRmqlsSYAfX0TGNvMTcxAGEmq/W4NrWE/l81yUozNym/RccOGoz4HmzksriQbb4O+at5u0O0/Z9z9WO0J1rfvWT40nXwiiDqTiGKtUZgrw8pxUt4bvTiXWdlbWJCKI/LsduHunnJL9sINB8dBs+Kw5WeBDEdM4Fgof9mnKKLbO+9yRUDxlLmkiLOE9riYrgHkiN4M0Vb9Lrw9lD+2sIkiAdIwcANANZhnVfNwPx/QuOhcOiVcpz6Uu+pS4KL+wtb+FXwaieUj/Fmd7PSu9eOS/0dXuLSppLZYOzMh40rTVnD2TPlFhwtyFO8FOk7fOBxU/Gc1jLnpcclJ2PP5ZYpqkMQWMf02GXpyfuI0+u2N79hAaywaYskBGAeaV4A/GXEmX+2QTI9NdEG1Zz6Vs+ww=
